In [20]:
import numpy as np

In [21]:
#numpy.array(object, dtype = None, copy = True, order = None, subok = False, ndmin = 0) 
a = np.array([1, 2, 3]) 
b = np.array([[1, 2, 3], [4, 5, 6]]) 
c = np.array([5,8,2], complex)

In [23]:
print(a)
print(b)
print(c)

[1 2 3]
[[1 2 3]
 [4 5 6]]
[5.+0.j 8.+0.j 2.+0.j]


In [24]:
arr = np.array([[1, 2, 3, 4], [4, 5, 6, 7], [9, 10, 11, 23]])  
arr.ndim #The ndim function can be used to find the dimensions of the array.

2

In [25]:
#itemsize helps finding the size of each item in the array   
d = np.array([[1,2,3]])  
print("Each item contains",d.itemsize,"bytes")  

Each item contains 4 bytes


In [26]:
#dtype helps finding the data type of each array item  
e = np.array([[1,2,3]])  
print("Each item is of the type",e.dtype) 

Each item is of the type int32


In [28]:
f = np.array([[1,2,3,4],[5,6,7,8]])  
print("Array Size:",f.size)  
print("Shape:",f.shape) #shape(rows, columns)

Array Size: 8
Shape: (2, 4)


In [29]:
g = np.array([[1,2],[3,4],[5,6]])  
print("printing the original array..")  
print(g)  
g=g.reshape(2,3)  
print("printing the reshaped array..")  
print(g)  

printing the original array..
[[1 2]
 [3 4]
 [5 6]]
printing the reshaped array..
[[1 2 3]
 [4 5 6]]


In [31]:
a = np.array([[1,2],[3,4],[5,6]])  
print(a[0,1])#2nd element from the 0th index
print(a[2,0])#0th element from the 2nd index

2
5


In [33]:
a=np.linspace(5,45,10) #prints 10 values which are evenly spaced over the given interval 5-15  
print(a) 

[ 5.          9.44444444 13.88888889 18.33333333 22.77777778 27.22222222
 31.66666667 36.11111111 40.55555556 45.        ]


In [34]:
a = np.array([1,2,3,10,15,4])  
print("The array:",a)  
print("The maximum element:",a.max())  
print("The minimum element:",a.min())  
print("The sum of the elements:",a.sum())  

The array: [ 1  2  3 10 15  4]
The maximum element: 15
The minimum element: 1
The sum of the elements: 35


In [35]:
#A multi-dimensional array is represented by the axis where axis-0 represents the columns and axis-1 represents the rows
a = np.array([[1,2,30],[10,15,4]])  
print("The array:",a)  
print("The maximum elements of columns:",a.max(axis = 0))   
print("The minimum element of rows",a.min(axis = 1))  
print("The sum of all rows",a.sum(axis = 1))  

The array: [[ 1  2 30]
 [10 15  4]]
The maximum elements of columns: [10 15 30]
The minimum element of rows [1 4]
The sum of all rows [33 29]


In [36]:
#The sqrt() and std() functions associated with the numpy array are used to find the square root and standard deviation of the array elements respectively.
a = np.array([[1,2,30],[10,15,4]])  
print(np.sqrt(a))  
print(np.std(a))  

[[1.         1.41421356 5.47722558]
 [3.16227766 3.87298335 2.        ]]
10.044346115546242


In [37]:
#The numpy module allows us to perform the arithmetic operations on multi-dimensional arrays directly.
a = np.array([[1,2,30],[10,15,4]])  
b = np.array([[1,2,3],[12, 19, 29]])  
print("Sum of array a and b\n",a+b)  
print("Product of array a and b\n",a*b)  
print("Division of array a and b\n",a/b)  

Sum of array a and b
 [[ 2  4 33]
 [22 34 33]]
Product of array a and b
 [[  1   4  90]
 [120 285 116]]
Division of array a and b
 [[ 1.          1.         10.        ]
 [ 0.83333333  0.78947368  0.13793103]]


In [38]:
#vertical stacking and horizontal stacking which allows us to concatenate two multi-dimensional arrays vertically or horizontally.
a = np.array([[1,2,30],[10,15,4]])  
b = np.array([[1,2,3],[12, 19, 29]])  
print("Arrays vertically concatenated\n",np.vstack((a,b)));  
print("Arrays horizontally concatenated\n",np.hstack((a,b)))  

Arrays vertically concatenated
 [[ 1  2 30]
 [10 15  4]
 [ 1  2  3]
 [12 19 29]]
Arrays horizontally concatenated
 [[ 1  2 30  1  2  3]
 [10 15  4 12 19 29]]


In [39]:
#numpy.dtype(object, align, copy) 
d = np.dtype(np.int32)  
print(d) 

int32


In [42]:
#a map-like (dictionary) data type which contains the mapping between the values.
d = np.dtype([('salary',np.float)])  
print(d)  
d=np.dtype([('salary',np.float)])  
arr = np.array([(10000.12,),(20000.50,)],dtype=d)  
print(arr['salary'])

[('salary', '<f8')]
[10000.12 20000.5 ]


C:\Users\İbrahim\AppData\Local\Temp\ipykernel_1096\1407920270.py:2: DeprecationWarning: `np.float` is a deprecated alias for the builtin `float`. To silence this warning, use `float` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.float64` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  d = np.dtype([('salary',np.float)])
C:\Users\İbrahim\AppData\Local\Temp\ipykernel_1096\1407920270.py:4: DeprecationWarning: `np.float` is a deprecated alias for the builtin `float`. To silence this warning, use `float` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.float64` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  d=np.dtype([('salary',np.float)])


In [44]:
#The empty routine is used to create an uninitialized array of specified shape and data type.
#np.empty(shape, dtype = float, order = 'C')
array = np.empty((3,2), dtype = int)  
print(array)    

[[ 1  2]
 [ 3 12]
 [19 29]]


In [45]:
#numpy array with the specified shape where each numpy array item is initialized to 0.
#numpy.zeros(shape, dtype = float, order = 'C')
array = np.zeros((6,7), dtype = int)  
print(array)  

[[0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]]


In [47]:
#create the numpy array with the specified shape where each numpy array item is initialized to 1
#numpy.ones(shape, dtype = none, order = 'C')  
ar = np.ones((5,5), dtype = int)  
print(ar)  

[[1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]]


In [49]:
#create an array by using the existing data in the form of lists, or tuples.
#numpy.asarray(sequence,  dtype = None, order = None)
l=[[1,2,3],[8,9,10]] 
a = np.asarray(l);  
print(type(a))  
print(a)  

<class 'numpy.ndarray'>
[[ 1  2  3]
 [ 8  9 10]]


In [51]:
#create an array by using the specified buffer.
#numpy.frombuffer(buffer, dtype = float, count = -1, offset = 0)
l = b'hello world'  
print(type(l))  
a = np.frombuffer(l, dtype = "S1")  
print(a)  
print(type(a))  

<class 'bytes'>
[b'h' b'e' b'l' b'l' b'o' b' ' b'w' b'o' b'r' b'l' b'd']
<class 'numpy.ndarray'>


In [53]:
#create a ndarray by using an iterable object. It returns a one-dimensional ndarray object.
#numpy.fromiter(iterable, dtype, count = - 1)  
list = [0,2,4,6]  
it = iter(list)  
x = np.fromiter(it, dtype = float)  
print(x)  
print(type(x))  

[0. 2. 4. 6.]
<class 'numpy.ndarray'>


In [54]:
#create an array by using the evenly spaced values over the given interval.
#numpy.arrange(start, stop, step, dtype)
arr = np.arange(6,10,2,float)  
print(arr)    

[6. 8.]


In [55]:
#returns evenly separated values fo an array over a specified period.
#numpy.linspace(start, stop, num, endpoint(bool), retstep(bool), dtype)  
arr = np.linspace(10, 20, 5)  
print("The array over the given range is ",arr)  

The array over the given range is  [10.  12.5 15.  17.5 20. ]


In [56]:
#creates an array by using the numbers that are evenly separated on a log scale.
#numpy.logspace(start, stop, num, endpoint(bool), base(bool), dtype)  
arr = np.logspace(10, 20, num = 5, endpoint = True)  
print("The array over the given range is ",arr)  

The array over the given range is  [1.00000000e+10 3.16227766e+12 1.00000000e+15 3.16227766e+17
 1.00000000e+20]


In [57]:
#numpy broadcasting - streches the smaller array with its values
a = np.array([[1,2,3,4],[2,4,5,6],[10,20,39,3]])  
b = np.array([2,4,6,8])  
print("\nprinting array a..")  
print(a)  
print("\nprinting array b..")  
print(b)  
print("\nAdding arrays a and b ..")  
c = a + b;  
print(c) 


printing array a..
[[ 1  2  3  4]
 [ 2  4  5  6]
 [10 20 39  3]]

printing array b..
[2 4 6 8]

Adding arrays a and b ..
[[ 3  6  9 12]
 [ 4  8 11 14]
 [12 24 45 11]]


In [59]:
#iterate over the given array using python standard Iterator interface.
a = np.array([[1,2,3,4],[2,4,5,6],[10,20,39,3]])  
print("Printing array:")  
print(a);  
print("Iterating over the array:")  
for x in np.nditer(a):  
    print(x,end=' ')  
#Order of the iteration doesn't follow any special ordering like row-major or column-order. However, it is intended to match the memory layout of the array.

Printing array:
[[ 1  2  3  4]
 [ 2  4  5  6]
 [10 20 39  3]]
Iterating over the array:
1 2 3 4 2 4 5 6 10 20 39 3 

In [60]:
#The bitwise and operation is performed on the corresponding bits of the binary representation of the operands.
a = 10  
b = 12  
print("binary representation of a:",bin(a))  
print("binary representation of b:",bin(b))  
print("Bitwise-and of a and b: ",np.bitwise_and(a,b))  

binary representation of a: 0b1010
binary representation of b: 0b1100
Bitwise-and of a and b:  8


In [64]:
a = 4
b = 2
print("binary representation of a:",bin(a))  
print("binary representation of b:",bin(b))  
print("Bitwise-or of a and b: ",np.bitwise_or(a,b)) 

binary representation of a: 0b100
binary representation of b: 0b10
Bitwise-or of a and b:  6


In [65]:
#It is used to calculate the bitwise not the operation of the given operand. The 2's complement is returned if the signed integer is passed in the function.
arr = np.array([20],dtype = np.uint8)  
print("Binary representation:",np.binary_repr(20,8))  
print(np.invert(arr))  
print("Binary representation: ", np.binary_repr(235,8))  

Binary representation: 00010100
[235]
Binary representation:  11101011


In [66]:
#It shifts the bits in the binary representation of the operand to the left by the specified position. An equal number of 0s are appended from the right.
print("left shift of 20 by 3 bits",np.left_shift(20, 3))  
print("Binary representation of 20 in 8 bits",np.binary_repr(20, 8))   
print("Binary representation of 160 in 8 bits",np.binary_repr(160,8))  

left shift of 20 by 3 bits 160
Binary representation of 20 in 8 bits 00010100
Binary representation of 160 in 8 bits 10100000


In [67]:
#numpy.char.add() method example 
print("Concatenating two string arrays:")  
print(np.char.add(['welcome','Hi'], [' to Javatpoint', ' read python'] ))

Concatenating two string arrays:
['welcome to Javatpoint' 'Hi read python']


In [68]:
#numpy.char.multiply() method example
print("Printing a string multiple times:")  
print(np.char.multiply("hello ",3))  

Printing a string multiple times:
hello hello hello 


In [69]:
#numpy.char.center() method example
print("Padding the string through left and right with the fill char *");  
#np.char.center(string, width, fillchar)  
print(np.char.center("Javatpoint", 20, '*'))  

Padding the string through left and right with the fill char *
*****Javatpoint*****


In [70]:
#capitalize(),title(),lower(),upper(),split(),splitlines(),strip(),join()
print(np.char.join(':','Merhabalar'))  

M:e:r:h:a:b:a:l:a:r


In [71]:
str = "Welcome to Javatpoint"  
print("Original String:",str)  
print("Modified String:",end=" ")  
print(np.char.replace(str, "Welcome to","www."))

Original String: Welcome to Javatpoint
Modified String: www. Javatpoint


In [72]:
enstr = np.char.encode("welcome to javatpoint", 'cp500')  
dstr =np.char.decode(enstr, 'cp500')  
print(enstr)  
print(dstr)  

b'\xa6\x85\x93\x83\x96\x94\x85@\xa3\x96@\x91\x81\xa5\x81\xa3\x97\x96\x89\x95\xa3'
welcome to javatpoint


In [73]:
#Trigonometric functions
arr = np.array([0, 30, 60, 90, 120, 150, 180])  
print("\nThe sin value of the angles",end = " ")  
print(np.sin(arr * np.pi/180))  
print("\nThe cosine value of the angles",end = " ")  
print(np.cos(arr * np.pi/180))  
print("\nThe tangent value of the angles",end = " ")  
print(np.tan(arr * np.pi/180)) 
#also arcsin(), arccos(), and arctan() functions return the trigonometric inverse of the specified angles.


The sin value of the angles [0.00000000e+00 5.00000000e-01 8.66025404e-01 1.00000000e+00
 8.66025404e-01 5.00000000e-01 1.22464680e-16]

The cosine value of the angles [ 1.00000000e+00  8.66025404e-01  5.00000000e-01  6.12323400e-17
 -5.00000000e-01 -8.66025404e-01 -1.00000000e+00]

The tangent value of the angles [ 0.00000000e+00  5.77350269e-01  1.73205081e+00  1.63312394e+16
 -1.73205081e+00 -5.77350269e-01 -1.22464680e-16]


In [74]:
#This function returns a decimal value rounded to a desired position of the decimal.
#numpy.around(num, decimals) 
arr = np.array([12.202, 90.23120, 123.020, 23.202])  
print("printing the original array values:",end = " ")  
print(arr)  
print("Array values rounded off to 2 decimal position",np.around(arr, 2))  
print("Array values rounded off to -1 decimal position",np.around(arr, -1))  

printing the original array values: [ 12.202   90.2312 123.02    23.202 ]
Array values rounded off to 2 decimal position [ 12.2   90.23 123.02  23.2 ]
Array values rounded off to -1 decimal position [ 10.  90. 120.  20.]


In [76]:
#This function is used to return the floor value of the input data which is the largest integer not greater than the input value.
arr = np.array([12.202, 90.83120, 123.020, 23.202])  
print(np.floor(arr))  

[ 12.  90. 123.  23.]


In [77]:
#this function is used to return the ceiling value of the array values which is the smallest integer value greater than the array element.
arr = np.array([12.202, 90.23120, 123.020, 23.202])  
print(np.ceil(arr)) 

[ 13.  91. 124.  24.]


In [78]:
#The numpy.amin() and numpy.amax() functions are used to find the minimum and maximum of the array elements along the specified axis respectively.
a = np.array([[2,10,20],[80,43,31],[22,43,10]])  
  
print("The original array:\n")  
print(a)  
  
print("\nThe minimum element among the array:",np.amin(a))  
print("The maximum element among the array:",np.amax(a))  
  
print("\nThe minimum element among the rows of array",np.amin(a,0))  
print("The maximum element among the rows of array",np.amax(a,0))  
  
print("\nThe minimum element among the columns of array",np.amin(a,1))  
print("The maximum element among the columns of array",np.amax(a,1)) 

The original array:

[[ 2 10 20]
 [80 43 31]
 [22 43 10]]

The minimum element among the array: 2
The maximum element among the array: 80

The minimum element among the rows of array [ 2 10 10]
The maximum element among the rows of array [80 43 31]

The minimum element among the columns of array [ 2 31 10]
The maximum element among the columns of array [20 80 43]


In [79]:
#return the range of values along an axis. - peak-to-peak
a = np.array([[2,10,20],[80,43,31],[22,43,10]])  
  
print("Original array:\n",a)  
print("\nptp value along axis 1:",np.ptp(a,1))  
print("ptp value along axis 0:",np.ptp(a,0))  

Original array:
 [[ 2 10 20]
 [80 43 31]
 [22 43 10]]

ptp value along axis 1: [18 49 33]
ptp value along axis 0: [78 33 21]


In [82]:
#numpy.percentile(input, q, axis)  
a = np.array([[2,48],[2,2],[2,2]])  
  
print("Array:\n",a)    
print("\nPercentile along axis 0",np.percentile(a, 10,0))   
print("Percentile along axis 1",np.percentile(a, 10, 1))  

Array:
 [[ 2 48]
 [ 2  2]
 [ 2  2]]

Percentile along axis 0 [2. 2.]
Percentile along axis 1 [6.6 2.  2. ]


In [83]:
#median, mean, avg functions
a = np.array([[1,2,3],[4,5,6],[7,8,9]])  
print("Array:\n",a)  
  
print("\nMedian of array along axis 0:",np.median(a,0))  
print("Mean of array along axis 0:",np.mean(a,0))  
print("Average of array along axis 1:",np.average(a,1)) 

Array:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]

Median of array along axis 0: [4. 5. 6.]
Mean of array along axis 0: [4. 5. 6.]
Average of array along axis 1: [2. 5. 8.]


In [84]:
#Sorting algorithm
#numpy.sort(a, axis, kind, order)
a = np.array([[10,2,3],[4,5,6],[7,8,9]])  
  
print("Sorting along the columns:")  
print(np.sort(a)) #(axis = 1) as default 
  
print("Sorting along the rows:")  
print(np.sort(a, 0))  
  
data_type = np.dtype([('name', 'S10'),('marks',int)])  
  
arr = np.array([('Mukesh',200),('John',251)],dtype = data_type)  
  
print("Sorting data ordered by name")  
  
print(np.sort(arr,order = 'name'))    

Sorting along the columns:
[[ 2  3 10]
 [ 4  5  6]
 [ 7  8  9]]
Sorting along the rows:
[[ 4  2  3]
 [ 7  5  6]
 [10  8  9]]
Sorting data ordered by name
[(b'John', 251) (b'Mukesh', 200)]


In [85]:
#numpy.argsort() - it returns an array of indices of data which is used to construct the array of sorted data
a = np.array([90, 29, 89, 12])  
print("Original array:\n",a)  
  
sort_ind = np.argsort(a)  
print("Printing indices of sorted data\n",sort_ind)  
  
sort_a = a[sort_ind]  
print("printing sorted array")  
  
for i in sort_ind:  
    print(a[i],end = " ")  

Original array:
 [90 29 89 12]
Printing indices of sorted data
 [3 1 2 0]
printing sorted array
12 29 89 90 

In [86]:
#numpy.lexsort() _This function is used to sort the array using the sequence of keys indirectly.
a = np.array(['a','b','c','d','e'])  
b = np.array([12, 90, 380, 12, 211])  
  
ind = np.lexsort((a,b))  
print("printing indices of sorted data")  
print(ind)  
  
print("using the indices to sort the array")  
for i in ind:  
    print(a[i],b[i]) 

printing indices of sorted data
[0 3 1 4 2]
using the indices to sort the array
a 12
d 12
b 90
e 211
c 380


In [87]:
#numpy.nonzero()
#This function is used to find the location of the non-zero elements from the array.
b = np.array([12, 90, 380, 12, 211])  
print("printing original array",b)  
  
print("printing location of the non-zero elements")  
print(b.nonzero())  

printing original array [ 12  90 380  12 211]
printing location of the non-zero elements
(array([0, 1, 2, 3, 4], dtype=int64),)


In [88]:
#numpy.where() - This function is used to return the indices of all the elements which satisfies a particular condition.
b = np.array([12, 90, 380, 12, 211])  
print(np.where(b>12))  
  
c = np.array([[20, 24],[21, 23]])  
print(np.where(c>20))  

(array([1, 2, 4], dtype=int64),)
(array([0, 1, 1], dtype=int64), array([1, 0, 1], dtype=int64))


In [89]:
#Array assigment
a = np.array([[1,2,3,4],[9,0,2,3],[1,2,3,19]])  
print("Original Array:\n",a)  
print("\nID of array a:",id(a))  
  
b = a   
print("\nmaking copy of the array a")  
print("\nID of b:",id(b))  
  
b.shape = 4,3;  
print("\nChanges on b also reflect to a:")  
print(a)  

Original Array:
 [[ 1  2  3  4]
 [ 9  0  2  3]
 [ 1  2  3 19]]

ID of array a: 2565285347664

making copy of the array a

ID of b: 2565285347664

Changes on b also reflect to a:
[[ 1  2  3]
 [ 4  9  0]
 [ 2  3  1]
 [ 2  3 19]]


In [90]:
#ndarray.view() method
#The ndarray.view() method returns the new array object which contains the same content as the original array does
a = np.array([[1,2,3,4],[9,0,2,3],[1,2,3,19]])  
print("Original Array:\n",a)  
print("\nID of array a:",id(a))  
  
b = a.view()  
print("\nID of b:",id(b))  
print("\nprinting the view b")  
print(b)  
  
b.shape = 4,3;  
print("\nChanges made to the view b do not reflect a")  
print("\nOriginal array \n",a)  
print("\nview\n",b)  

Original Array:
 [[ 1  2  3  4]
 [ 9  0  2  3]
 [ 1  2  3 19]]

ID of array a: 2565285215856

ID of b: 2565285351024

printing the view b
[[ 1  2  3  4]
 [ 9  0  2  3]
 [ 1  2  3 19]]

Changes made to the view b do not reflect a

Original array 
 [[ 1  2  3  4]
 [ 9  0  2  3]
 [ 1  2  3 19]]

view
 [[ 1  2  3]
 [ 4  9  0]
 [ 2  3  1]
 [ 2  3 19]]


In [91]:
#ndarray.copy() method
#It returns the deep copy of the original array which doesn't share any memory with the original array. 
#The modification made to the deep copy of the original array doesn't reflect the original array.
a = np.array([[1,2,3,4],[9,0,2,3],[1,2,3,19]])  
print("Original Array:\n",a)  
print("\nID of array a:",id(a))  
  
b = a.copy()  
print("\nID of b:",id(b))  
print("\nprinting the deep copy b")  
print(b)  
  
b.shape = 4,3;  
print("\nChanges made to the copy b do not reflect a")  
print("\nOriginal array \n",a)  
print("\nCopy\n",b)  

Original Array:
 [[ 1  2  3  4]
 [ 9  0  2  3]
 [ 1  2  3 19]]

ID of array a: 2565285308432

ID of b: 2565285309104

printing the deep copy b
[[ 1  2  3  4]
 [ 9  0  2  3]
 [ 1  2  3 19]]

Changes made to the copy b do not reflect a

Original array 
 [[ 1  2  3  4]
 [ 9  0  2  3]
 [ 1  2  3 19]]

Copy
 [[ 1  2  3]
 [ 4  9  0]
 [ 2  3  1]
 [ 2  3 19]]


In [92]:
#numpy.matlib.empty() function
#This function is used to return a new matrix with the uninitialized entries.
#numpy.matlib.empty(shape, dtype, order)  
import numpy.matlib  
print(numpy.matlib.zeros((4,3)))  

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [93]:
#matrix by ones
import numpy.matlib  
print(numpy.matlib.ones((2,2)))  

[[1. 1.]
 [1. 1.]]


In [98]:
#numpy.matlib.eye() function
#This function returns a matrix with the diagonal elements initialized to 1 and zero elsewhere.
#numpy.matlib.eye(n, m, k, dtype)   
print(numpy.matlib.eye(n = 3, M = 3, k = 0, dtype = int))
      
#numpy.matlib.identity() function
#This function is used to return an identity matrix of the given size. An identity matrix is the one with diagonal elements initializes to 1 and all other elements to zero.
print(numpy.matlib.identity(5, dtype = int))  

#numpy.matlib.rand() function
#This function is used to generate a matrix where all the entries are initialized with random values.
print(numpy.matlib.rand(3,3))  


[[1 0 0]
 [0 1 0]
 [0 0 1]]
[[1 0 0 0 0]
 [0 1 0 0 0]
 [0 0 1 0 0]
 [0 0 0 1 0]
 [0 0 0 0 1]]
[[0.98709072 0.54915096 0.55368519]
 [0.64774759 0.44840062 0.68921848]
 [0.83093119 0.93655788 0.93716736]]


In [99]:
#numpy.dot() function
#This function is used to return the dot product of the two matrices. It is similar to the matrix multiplication.
a = np.array([[100,200],[23,12]])  
b = np.array([[10,20],[12,21]])  
dot = np.dot(a,b)  
print(dot)  

[[3400 6200]
 [ 374  712]]


In [100]:
#numpy.vdot() function
#This function is used to calculate the dot product of two vectors.
a = np.array([[100,200],[23,12]])  
b = np.array([[10,20],[12,21]])  
vdot = np.vdot(a,b)  
print(vdot)  

5528


In [101]:
#numpy.inner() function
#This function returns the sum of the product of inner elements of the one-dimensional array. For n-dimensional arrays, it returns the sum of the product of elements over the last axis.
a = np.array([1,2,3,4,5,6])  
b = np.array([23,23,12,2,1,2])  
inner = np.inner(a,b)  
print(inner)  

130


In [102]:
#numpy.matmul() function
#It is used to return the multiplication of the two matrices. It gives an error if the shape of both matrices is not aligned for multiplication.
a = np.array([[1,2,3],[4,5,6],[7,8,9]])  
b = np.array([[23,23,12],[2,1,2],[7,8,9]])  
mul = np.matmul(a,b)  
print(mul) 

[[ 48  49  43]
 [144 145 112]
 [240 241 181]]


In [103]:
#The numpy.linalg.det() function is used to calculate the determinant of the matrix
a = np.array([[1,2],[3,4]])  
print(np.linalg.det(a)) 

-2.0000000000000004


In [104]:
#numpy.linalg.solve() function
#This function is used to solve a quadratic equation where values can be given in the form of the matrix.
a = np.array([[1,2],[3,4]])  
b = np.array([[1,2],[3,4]])  
print(np.linalg.solve(a, b)) 

[[1.00000000e+00 0.00000000e+00]
 [8.32667268e-17 1.00000000e+00]]


In [105]:
#numpy.linalg.inv() function
#This function is used to calculate the multiplicative inverse of the input matrix.
a = np.array([[1,2],[3,4]])  
print("Original array:\n",a)  
b = np.linalg.inv(a)  
print("Inverse:\n",b)  

Original array:
 [[1 2]
 [3 4]]
Inverse:
 [[-2.   1. ]
 [ 1.5 -0.5]]


In [106]:
#Matrix multiplication
array1=np.array([[1,2,3],[4,5,6],[7,8,9]],ndmin=3)  
array2=np.array([[9,8,7],[6,5,4],[3,2,1]],ndmin=3)  
result=np.multiply(array1,array2)  
result

array([[[ 9, 16, 21],
        [24, 25, 24],
        [21, 16,  9]]])